# Generated by Django 3.1.3 on 2020-12-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(default=1, verbose_name='性别')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='邮件')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='电话')),
                ('headPortrait', models.ImageField(blank=True, height_field=60, null=True, upload_to='', verbose_name='头像', width_field=50)),
                ('identityCard', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='身份证')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('type', models.IntegerField(default=1, verbose_name='账号类型')),
            ],
        ),
    ]
