# Generated by Django 3.1.3 on 2020-12-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postStatus',
            field=models.IntegerField(default=1, verbose_name='职务状态'),
        ),
    ]
