# Generated by Django 3.1.3 on 2020-12-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_poststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creatTime',
            field=models.DateTimeField(default='1970-1-1 00:00:00', verbose_name='注册时间'),
            preserve_default=False,
        ),
    ]
