# Generated by Django 3.1.3 on 2020-12-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_creattime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(default='大专', max_length=20, verbose_name='学历'),
            preserve_default=False,
        ),
    ]
