# Generated by Django 3.1.3 on 2021-01-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L1_Task_create', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.IntegerField(default=0, verbose_name='任务状态'),
        ),
    ]
