# Generated by Django 3.1.3 on 2021-01-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='项目名')),
                ('description', models.TextField(max_length=5000, null=True, verbose_name='项目简介')),
                ('note', models.TextField(max_length=5000, verbose_name='备注')),
                ('schedule', models.TextField(default='0/0', max_length=100, verbose_name='项目进度')),
                ('source', models.TextField(max_length=200, null=True, verbose_name='来源')),
                ('state', models.IntegerField(default=0, null=True, verbose_name='状态：0:计划(创建未启动）1:启动(进行中),2:完成，3：暂停，4：废除(终止）')),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.company', verbose_name='公司id')),
            ],
        ),
    ]
